// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package kvfile

import (
	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *KV) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_12ee7be02f254da2_1 = 2

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_12ee7be02f254da2_1 uint32
	totalEncodedFields0zgensym_12ee7be02f254da2_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_12ee7be02f254da2_1 := totalEncodedFields0zgensym_12ee7be02f254da2_1
	missingFieldsLeft0zgensym_12ee7be02f254da2_1 := maxFields0zgensym_12ee7be02f254da2_1 - totalEncodedFields0zgensym_12ee7be02f254da2_1

	var nextMiss0zgensym_12ee7be02f254da2_1 int32 = -1
	var found0zgensym_12ee7be02f254da2_1 [maxFields0zgensym_12ee7be02f254da2_1]bool
	var curField0zgensym_12ee7be02f254da2_1 string

doneWithStruct0zgensym_12ee7be02f254da2_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_12ee7be02f254da2_1 > 0 || missingFieldsLeft0zgensym_12ee7be02f254da2_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_12ee7be02f254da2_1, missingFieldsLeft0zgensym_12ee7be02f254da2_1, msgp.ShowFound(found0zgensym_12ee7be02f254da2_1[:]), decodeMsgFieldOrder0zgensym_12ee7be02f254da2_1)
		if encodedFieldsLeft0zgensym_12ee7be02f254da2_1 > 0 {
			encodedFieldsLeft0zgensym_12ee7be02f254da2_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_12ee7be02f254da2_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_12ee7be02f254da2_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_12ee7be02f254da2_1 = 0
			}
			for nextMiss0zgensym_12ee7be02f254da2_1 < maxFields0zgensym_12ee7be02f254da2_1 && (found0zgensym_12ee7be02f254da2_1[nextMiss0zgensym_12ee7be02f254da2_1] || decodeMsgFieldSkip0zgensym_12ee7be02f254da2_1[nextMiss0zgensym_12ee7be02f254da2_1]) {
				nextMiss0zgensym_12ee7be02f254da2_1++
			}
			if nextMiss0zgensym_12ee7be02f254da2_1 == maxFields0zgensym_12ee7be02f254da2_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_12ee7be02f254da2_1
			}
			missingFieldsLeft0zgensym_12ee7be02f254da2_1--
			curField0zgensym_12ee7be02f254da2_1 = decodeMsgFieldOrder0zgensym_12ee7be02f254da2_1[nextMiss0zgensym_12ee7be02f254da2_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_12ee7be02f254da2_1)
		switch curField0zgensym_12ee7be02f254da2_1 {
		// -- templateDecodeMsg ends here --

		case "Key_zid00_bin":
			found0zgensym_12ee7be02f254da2_1[0] = true
			z.Key, err = dc.ReadBytes(z.Key)
			if err != nil {
				return
			}
		case "Val_zid01_bin":
			found0zgensym_12ee7be02f254da2_1[1] = true
			z.Val, err = dc.ReadBytes(z.Val)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_12ee7be02f254da2_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KV
var decodeMsgFieldOrder0zgensym_12ee7be02f254da2_1 = []string{"Key_zid00_bin", "Val_zid01_bin"}

var decodeMsgFieldSkip0zgensym_12ee7be02f254da2_1 = []bool{false, false}

// fieldsNotEmpty supports omitempty tags
func (z *KV) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 2
	}
	var fieldsInUse uint32 = 2
	isempty[0] = (len(z.Key) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Val) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *KV) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_12ee7be02f254da2_2 [2]bool
	fieldsInUse_zgensym_12ee7be02f254da2_3 := z.fieldsNotEmpty(empty_zgensym_12ee7be02f254da2_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_12ee7be02f254da2_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'KV'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x4b, 0x56})
	if err != nil {
		return err
	}

	if !empty_zgensym_12ee7be02f254da2_2[0] {
		// write "Key_zid00_bin"
		err = en.Append(0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Key)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_12ee7be02f254da2_2[1] {
		// write "Val_zid01_bin"
		err = en.Append(0xad, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Val)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *KV) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [2]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Key_zid00_bin"
		o = append(o, 0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Key)
	}

	if !empty[1] {
		// string "Val_zid01_bin"
		o = append(o, 0xad, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Val)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KV) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *KV) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_12ee7be02f254da2_5 = 2

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_12ee7be02f254da2_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_12ee7be02f254da2_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_12ee7be02f254da2_5 := totalEncodedFields4zgensym_12ee7be02f254da2_5
	missingFieldsLeft4zgensym_12ee7be02f254da2_5 := maxFields4zgensym_12ee7be02f254da2_5 - totalEncodedFields4zgensym_12ee7be02f254da2_5

	var nextMiss4zgensym_12ee7be02f254da2_5 int32 = -1
	var found4zgensym_12ee7be02f254da2_5 [maxFields4zgensym_12ee7be02f254da2_5]bool
	var curField4zgensym_12ee7be02f254da2_5 string

doneWithStruct4zgensym_12ee7be02f254da2_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_12ee7be02f254da2_5 > 0 || missingFieldsLeft4zgensym_12ee7be02f254da2_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_12ee7be02f254da2_5, missingFieldsLeft4zgensym_12ee7be02f254da2_5, msgp.ShowFound(found4zgensym_12ee7be02f254da2_5[:]), unmarshalMsgFieldOrder4zgensym_12ee7be02f254da2_5)
		if encodedFieldsLeft4zgensym_12ee7be02f254da2_5 > 0 {
			encodedFieldsLeft4zgensym_12ee7be02f254da2_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_12ee7be02f254da2_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_12ee7be02f254da2_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_12ee7be02f254da2_5 = 0
			}
			for nextMiss4zgensym_12ee7be02f254da2_5 < maxFields4zgensym_12ee7be02f254da2_5 && (found4zgensym_12ee7be02f254da2_5[nextMiss4zgensym_12ee7be02f254da2_5] || unmarshalMsgFieldSkip4zgensym_12ee7be02f254da2_5[nextMiss4zgensym_12ee7be02f254da2_5]) {
				nextMiss4zgensym_12ee7be02f254da2_5++
			}
			if nextMiss4zgensym_12ee7be02f254da2_5 == maxFields4zgensym_12ee7be02f254da2_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_12ee7be02f254da2_5
			}
			missingFieldsLeft4zgensym_12ee7be02f254da2_5--
			curField4zgensym_12ee7be02f254da2_5 = unmarshalMsgFieldOrder4zgensym_12ee7be02f254da2_5[nextMiss4zgensym_12ee7be02f254da2_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_12ee7be02f254da2_5)
		switch curField4zgensym_12ee7be02f254da2_5 {
		// -- templateUnmarshalMsg ends here --

		case "Key_zid00_bin":
			found4zgensym_12ee7be02f254da2_5[0] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Key = z.Key[:0]
			} else {
				z.Key, bts, err = nbs.ReadBytesBytes(bts, z.Key)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		case "Val_zid01_bin":
			found4zgensym_12ee7be02f254da2_5[1] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Val = z.Val[:0]
			} else {
				z.Val, bts, err = nbs.ReadBytesBytes(bts, z.Val)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_12ee7be02f254da2_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KV
var unmarshalMsgFieldOrder4zgensym_12ee7be02f254da2_5 = []string{"Key_zid00_bin", "Val_zid01_bin"}

var unmarshalMsgFieldSkip4zgensym_12ee7be02f254da2_5 = []bool{false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *KV) Msgsize() (s int) {
	s = 1 + 14 + msgp.BytesPrefixSize + len(z.Key) + 14 + msgp.BytesPrefixSize + len(z.Val)
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *KVFile) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields7zgensym_12ee7be02f254da2_8 = 1

	// -- templateDecodeMsg starts here--
	var totalEncodedFields7zgensym_12ee7be02f254da2_8 uint32
	totalEncodedFields7zgensym_12ee7be02f254da2_8, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft7zgensym_12ee7be02f254da2_8 := totalEncodedFields7zgensym_12ee7be02f254da2_8
	missingFieldsLeft7zgensym_12ee7be02f254da2_8 := maxFields7zgensym_12ee7be02f254da2_8 - totalEncodedFields7zgensym_12ee7be02f254da2_8

	var nextMiss7zgensym_12ee7be02f254da2_8 int32 = -1
	var found7zgensym_12ee7be02f254da2_8 [maxFields7zgensym_12ee7be02f254da2_8]bool
	var curField7zgensym_12ee7be02f254da2_8 string

doneWithStruct7zgensym_12ee7be02f254da2_8:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft7zgensym_12ee7be02f254da2_8 > 0 || missingFieldsLeft7zgensym_12ee7be02f254da2_8 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft7zgensym_12ee7be02f254da2_8, missingFieldsLeft7zgensym_12ee7be02f254da2_8, msgp.ShowFound(found7zgensym_12ee7be02f254da2_8[:]), decodeMsgFieldOrder7zgensym_12ee7be02f254da2_8)
		if encodedFieldsLeft7zgensym_12ee7be02f254da2_8 > 0 {
			encodedFieldsLeft7zgensym_12ee7be02f254da2_8--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField7zgensym_12ee7be02f254da2_8 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss7zgensym_12ee7be02f254da2_8 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss7zgensym_12ee7be02f254da2_8 = 0
			}
			for nextMiss7zgensym_12ee7be02f254da2_8 < maxFields7zgensym_12ee7be02f254da2_8 && (found7zgensym_12ee7be02f254da2_8[nextMiss7zgensym_12ee7be02f254da2_8] || decodeMsgFieldSkip7zgensym_12ee7be02f254da2_8[nextMiss7zgensym_12ee7be02f254da2_8]) {
				nextMiss7zgensym_12ee7be02f254da2_8++
			}
			if nextMiss7zgensym_12ee7be02f254da2_8 == maxFields7zgensym_12ee7be02f254da2_8 {
				// filled all the empty fields!
				break doneWithStruct7zgensym_12ee7be02f254da2_8
			}
			missingFieldsLeft7zgensym_12ee7be02f254da2_8--
			curField7zgensym_12ee7be02f254da2_8 = decodeMsgFieldOrder7zgensym_12ee7be02f254da2_8[nextMiss7zgensym_12ee7be02f254da2_8]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField7zgensym_12ee7be02f254da2_8)
		switch curField7zgensym_12ee7be02f254da2_8 {
		// -- templateDecodeMsg ends here --

		case "Payload_zid00_slc":
			found7zgensym_12ee7be02f254da2_8[0] = true
			var zgensym_12ee7be02f254da2_9 uint32
			zgensym_12ee7be02f254da2_9, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.Payload) >= int(zgensym_12ee7be02f254da2_9) {
				z.Payload = (z.Payload)[:zgensym_12ee7be02f254da2_9]
			} else {
				z.Payload = make([]*KV, zgensym_12ee7be02f254da2_9)
			}
			for zgensym_12ee7be02f254da2_6 := range z.Payload {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}

					z.Payload[zgensym_12ee7be02f254da2_6] = nil
				} else if kptr, dup := dc.DedupReadIsDup("z.Payload[zgensym_12ee7be02f254da2_6]", "*KV"); dup {
					z.Payload[zgensym_12ee7be02f254da2_6] = kptr.(*KV)
				} else {
					if z.Payload[zgensym_12ee7be02f254da2_6] == nil {
						z.Payload[zgensym_12ee7be02f254da2_6] = new(KV)
					}
					dc.DedupIndexEachPtr(z.Payload[zgensym_12ee7be02f254da2_6])

					const maxFields10zgensym_12ee7be02f254da2_11 = 2

					// -- templateDecodeMsg starts here--
					var totalEncodedFields10zgensym_12ee7be02f254da2_11 uint32
					totalEncodedFields10zgensym_12ee7be02f254da2_11, err = dc.ReadMapHeader()
					if err != nil {
						return
					}
					encodedFieldsLeft10zgensym_12ee7be02f254da2_11 := totalEncodedFields10zgensym_12ee7be02f254da2_11
					missingFieldsLeft10zgensym_12ee7be02f254da2_11 := maxFields10zgensym_12ee7be02f254da2_11 - totalEncodedFields10zgensym_12ee7be02f254da2_11

					var nextMiss10zgensym_12ee7be02f254da2_11 int32 = -1
					var found10zgensym_12ee7be02f254da2_11 [maxFields10zgensym_12ee7be02f254da2_11]bool
					var curField10zgensym_12ee7be02f254da2_11 string

				doneWithStruct10zgensym_12ee7be02f254da2_11:
					// First fill all the encoded fields, then
					// treat the remaining, missing fields, as Nil.
					for encodedFieldsLeft10zgensym_12ee7be02f254da2_11 > 0 || missingFieldsLeft10zgensym_12ee7be02f254da2_11 > 0 {
						//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft10zgensym_12ee7be02f254da2_11, missingFieldsLeft10zgensym_12ee7be02f254da2_11, msgp.ShowFound(found10zgensym_12ee7be02f254da2_11[:]), decodeMsgFieldOrder10zgensym_12ee7be02f254da2_11)
						if encodedFieldsLeft10zgensym_12ee7be02f254da2_11 > 0 {
							encodedFieldsLeft10zgensym_12ee7be02f254da2_11--
							field, err = dc.ReadMapKeyPtr()
							if err != nil {
								return
							}
							curField10zgensym_12ee7be02f254da2_11 = msgp.UnsafeString(field)
						} else {
							//missing fields need handling
							if nextMiss10zgensym_12ee7be02f254da2_11 < 0 {
								// tell the reader to only give us Nils
								// until further notice.
								dc.PushAlwaysNil()
								nextMiss10zgensym_12ee7be02f254da2_11 = 0
							}
							for nextMiss10zgensym_12ee7be02f254da2_11 < maxFields10zgensym_12ee7be02f254da2_11 && (found10zgensym_12ee7be02f254da2_11[nextMiss10zgensym_12ee7be02f254da2_11] || decodeMsgFieldSkip10zgensym_12ee7be02f254da2_11[nextMiss10zgensym_12ee7be02f254da2_11]) {
								nextMiss10zgensym_12ee7be02f254da2_11++
							}
							if nextMiss10zgensym_12ee7be02f254da2_11 == maxFields10zgensym_12ee7be02f254da2_11 {
								// filled all the empty fields!
								break doneWithStruct10zgensym_12ee7be02f254da2_11
							}
							missingFieldsLeft10zgensym_12ee7be02f254da2_11--
							curField10zgensym_12ee7be02f254da2_11 = decodeMsgFieldOrder10zgensym_12ee7be02f254da2_11[nextMiss10zgensym_12ee7be02f254da2_11]
						}
						//fmt.Printf("switching on curField: '%v'\n", curField10zgensym_12ee7be02f254da2_11)
						switch curField10zgensym_12ee7be02f254da2_11 {
						// -- templateDecodeMsg ends here --

						case "Key_zid00_bin":
							found10zgensym_12ee7be02f254da2_11[0] = true
							z.Payload[zgensym_12ee7be02f254da2_6].Key, err = dc.ReadBytes(z.Payload[zgensym_12ee7be02f254da2_6].Key)
							if err != nil {
								return
							}
						case "Val_zid01_bin":
							found10zgensym_12ee7be02f254da2_11[1] = true
							z.Payload[zgensym_12ee7be02f254da2_6].Val, err = dc.ReadBytes(z.Payload[zgensym_12ee7be02f254da2_6].Val)
							if err != nil {
								return
							}
						default:
							err = dc.Skip()
							if err != nil {
								return
							}
						}
					}
					if nextMiss10zgensym_12ee7be02f254da2_11 != -1 {
						dc.PopAlwaysNil()
					}

				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss7zgensym_12ee7be02f254da2_8 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KVFile
var decodeMsgFieldOrder7zgensym_12ee7be02f254da2_8 = []string{"Payload_zid00_slc"}

var decodeMsgFieldSkip7zgensym_12ee7be02f254da2_8 = []bool{false}

// fields of KV
var decodeMsgFieldOrder10zgensym_12ee7be02f254da2_11 = []string{"Key_zid00_bin", "Val_zid01_bin"}

var decodeMsgFieldSkip10zgensym_12ee7be02f254da2_11 = []bool{false, false}

// fieldsNotEmpty supports omitempty tags
func (z *KVFile) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 1
	}
	var fieldsInUse uint32 = 1
	isempty[0] = (len(z.Payload) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *KVFile) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_12ee7be02f254da2_12 [1]bool
	fieldsInUse_zgensym_12ee7be02f254da2_13 := z.fieldsNotEmpty(empty_zgensym_12ee7be02f254da2_12[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_12ee7be02f254da2_13 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'KVFile'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x4b, 0x56, 0x46, 0x69, 0x6c, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_12ee7be02f254da2_12[0] {
		// write "Payload_zid00_slc"
		err = en.Append(0xb1, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.Payload)))
		if err != nil {
			return
		}
		for zgensym_12ee7be02f254da2_6 := range z.Payload {
			// gPtr.encodeGen():

			if z.Payload[zgensym_12ee7be02f254da2_6] == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// record the pointer for deduplication
				var dup bool
				dup, err = en.DedupWriteIsDup(z.Payload[zgensym_12ee7be02f254da2_6])
				if err != nil {
					return
				}
				if !dup {

					// honor the omitempty tags
					var empty_zgensym_12ee7be02f254da2_14 [2]bool
					fieldsInUse_zgensym_12ee7be02f254da2_15 := z.Payload[zgensym_12ee7be02f254da2_6].fieldsNotEmpty(empty_zgensym_12ee7be02f254da2_14[:])

					// map header
					err = en.WriteMapHeader(fieldsInUse_zgensym_12ee7be02f254da2_15 + 1)
					if err != nil {
						return err
					}

					// runtime struct type identification for 'KV'
					err = en.Append(0xa1, 0x40)
					if err != nil {
						return err
					}
					err = en.WriteStringFromBytes([]byte{0x4b, 0x56})
					if err != nil {
						return err
					}

					if !empty_zgensym_12ee7be02f254da2_14[0] {
						// write "Key_zid00_bin"
						err = en.Append(0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
						if err != nil {
							return err
						}
						err = en.WriteBytes(z.Payload[zgensym_12ee7be02f254da2_6].Key)
						if err != nil {
							return
						}
					}

					if !empty_zgensym_12ee7be02f254da2_14[1] {
						// write "Val_zid01_bin"
						err = en.Append(0xad, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
						if err != nil {
							return err
						}
						err = en.WriteBytes(z.Payload[zgensym_12ee7be02f254da2_6].Val)
						if err != nil {
							return
						}
					}

				}
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *KVFile) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [1]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Payload_zid00_slc"
		o = append(o, 0xb1, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Payload)))
		for zgensym_12ee7be02f254da2_6 := range z.Payload {
			// marshalGen.gPtr()

			if z.Payload[zgensym_12ee7be02f254da2_6] == nil {
				o = msgp.AppendNil(o)
			} else {
				// hmm.. no en, no place to check en.DedupWriteIsDup(z)

				// honor the omitempty tags
				var empty [2]bool
				fieldsInUse := z.Payload[zgensym_12ee7be02f254da2_6].fieldsNotEmpty(empty[:])
				o = msgp.AppendMapHeader(o, fieldsInUse)

				if !empty[0] {
					// string "Key_zid00_bin"
					o = append(o, 0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
					o = msgp.AppendBytes(o, z.Payload[zgensym_12ee7be02f254da2_6].Key)
				}

				if !empty[1] {
					// string "Val_zid01_bin"
					o = append(o, 0xad, 0x56, 0x61, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
					o = msgp.AppendBytes(o, z.Payload[zgensym_12ee7be02f254da2_6].Val)
				}

			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KVFile) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *KVFile) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields16zgensym_12ee7be02f254da2_17 = 1

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields16zgensym_12ee7be02f254da2_17 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields16zgensym_12ee7be02f254da2_17, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft16zgensym_12ee7be02f254da2_17 := totalEncodedFields16zgensym_12ee7be02f254da2_17
	missingFieldsLeft16zgensym_12ee7be02f254da2_17 := maxFields16zgensym_12ee7be02f254da2_17 - totalEncodedFields16zgensym_12ee7be02f254da2_17

	var nextMiss16zgensym_12ee7be02f254da2_17 int32 = -1
	var found16zgensym_12ee7be02f254da2_17 [maxFields16zgensym_12ee7be02f254da2_17]bool
	var curField16zgensym_12ee7be02f254da2_17 string

doneWithStruct16zgensym_12ee7be02f254da2_17:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft16zgensym_12ee7be02f254da2_17 > 0 || missingFieldsLeft16zgensym_12ee7be02f254da2_17 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft16zgensym_12ee7be02f254da2_17, missingFieldsLeft16zgensym_12ee7be02f254da2_17, msgp.ShowFound(found16zgensym_12ee7be02f254da2_17[:]), unmarshalMsgFieldOrder16zgensym_12ee7be02f254da2_17)
		if encodedFieldsLeft16zgensym_12ee7be02f254da2_17 > 0 {
			encodedFieldsLeft16zgensym_12ee7be02f254da2_17--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField16zgensym_12ee7be02f254da2_17 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss16zgensym_12ee7be02f254da2_17 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss16zgensym_12ee7be02f254da2_17 = 0
			}
			for nextMiss16zgensym_12ee7be02f254da2_17 < maxFields16zgensym_12ee7be02f254da2_17 && (found16zgensym_12ee7be02f254da2_17[nextMiss16zgensym_12ee7be02f254da2_17] || unmarshalMsgFieldSkip16zgensym_12ee7be02f254da2_17[nextMiss16zgensym_12ee7be02f254da2_17]) {
				nextMiss16zgensym_12ee7be02f254da2_17++
			}
			if nextMiss16zgensym_12ee7be02f254da2_17 == maxFields16zgensym_12ee7be02f254da2_17 {
				// filled all the empty fields!
				break doneWithStruct16zgensym_12ee7be02f254da2_17
			}
			missingFieldsLeft16zgensym_12ee7be02f254da2_17--
			curField16zgensym_12ee7be02f254da2_17 = unmarshalMsgFieldOrder16zgensym_12ee7be02f254da2_17[nextMiss16zgensym_12ee7be02f254da2_17]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField16zgensym_12ee7be02f254da2_17)
		switch curField16zgensym_12ee7be02f254da2_17 {
		// -- templateUnmarshalMsg ends here --

		case "Payload_zid00_slc":
			found16zgensym_12ee7be02f254da2_17[0] = true
			if nbs.AlwaysNil {
				(z.Payload) = (z.Payload)[:0]
			} else {

				var zgensym_12ee7be02f254da2_18 uint32
				zgensym_12ee7be02f254da2_18, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.Payload) >= int(zgensym_12ee7be02f254da2_18) {
					z.Payload = (z.Payload)[:zgensym_12ee7be02f254da2_18]
				} else {
					z.Payload = make([]*KV, zgensym_12ee7be02f254da2_18)
				}
				for zgensym_12ee7be02f254da2_6 := range z.Payload {
					// default gPtr logic.
					if nbs.PeekNil(bts) && z.Payload[zgensym_12ee7be02f254da2_6] == nil {
						// consume the nil
						bts, err = nbs.ReadNilBytes(bts)
						if err != nil {
							return
						}
					} else {
						// read as-if the wire has bytes, letting nbs take care of nils.

						if z.Payload[zgensym_12ee7be02f254da2_6] == nil {
							z.Payload[zgensym_12ee7be02f254da2_6] = new(KV)
						}

						const maxFields19zgensym_12ee7be02f254da2_20 = 2

						// -- templateUnmarshalMsg starts here--
						var totalEncodedFields19zgensym_12ee7be02f254da2_20 uint32
						if !nbs.AlwaysNil {
							totalEncodedFields19zgensym_12ee7be02f254da2_20, bts, err = nbs.ReadMapHeaderBytes(bts)
							if err != nil {
								return
							}
						}
						encodedFieldsLeft19zgensym_12ee7be02f254da2_20 := totalEncodedFields19zgensym_12ee7be02f254da2_20
						missingFieldsLeft19zgensym_12ee7be02f254da2_20 := maxFields19zgensym_12ee7be02f254da2_20 - totalEncodedFields19zgensym_12ee7be02f254da2_20

						var nextMiss19zgensym_12ee7be02f254da2_20 int32 = -1
						var found19zgensym_12ee7be02f254da2_20 [maxFields19zgensym_12ee7be02f254da2_20]bool
						var curField19zgensym_12ee7be02f254da2_20 string

					doneWithStruct19zgensym_12ee7be02f254da2_20:
						// First fill all the encoded fields, then
						// treat the remaining, missing fields, as Nil.
						for encodedFieldsLeft19zgensym_12ee7be02f254da2_20 > 0 || missingFieldsLeft19zgensym_12ee7be02f254da2_20 > 0 {
							//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft19zgensym_12ee7be02f254da2_20, missingFieldsLeft19zgensym_12ee7be02f254da2_20, msgp.ShowFound(found19zgensym_12ee7be02f254da2_20[:]), unmarshalMsgFieldOrder19zgensym_12ee7be02f254da2_20)
							if encodedFieldsLeft19zgensym_12ee7be02f254da2_20 > 0 {
								encodedFieldsLeft19zgensym_12ee7be02f254da2_20--
								field, bts, err = nbs.ReadMapKeyZC(bts)
								if err != nil {
									return
								}
								curField19zgensym_12ee7be02f254da2_20 = msgp.UnsafeString(field)
							} else {
								//missing fields need handling
								if nextMiss19zgensym_12ee7be02f254da2_20 < 0 {
									// set bts to contain just mnil (0xc0)
									bts = nbs.PushAlwaysNil(bts)
									nextMiss19zgensym_12ee7be02f254da2_20 = 0
								}
								for nextMiss19zgensym_12ee7be02f254da2_20 < maxFields19zgensym_12ee7be02f254da2_20 && (found19zgensym_12ee7be02f254da2_20[nextMiss19zgensym_12ee7be02f254da2_20] || unmarshalMsgFieldSkip19zgensym_12ee7be02f254da2_20[nextMiss19zgensym_12ee7be02f254da2_20]) {
									nextMiss19zgensym_12ee7be02f254da2_20++
								}
								if nextMiss19zgensym_12ee7be02f254da2_20 == maxFields19zgensym_12ee7be02f254da2_20 {
									// filled all the empty fields!
									break doneWithStruct19zgensym_12ee7be02f254da2_20
								}
								missingFieldsLeft19zgensym_12ee7be02f254da2_20--
								curField19zgensym_12ee7be02f254da2_20 = unmarshalMsgFieldOrder19zgensym_12ee7be02f254da2_20[nextMiss19zgensym_12ee7be02f254da2_20]
							}
							//fmt.Printf("switching on curField: '%v'\n", curField19zgensym_12ee7be02f254da2_20)
							switch curField19zgensym_12ee7be02f254da2_20 {
							// -- templateUnmarshalMsg ends here --

							case "Key_zid00_bin":
								found19zgensym_12ee7be02f254da2_20[0] = true
								if nbs.AlwaysNil || msgp.IsNil(bts) {
									if !nbs.AlwaysNil {
										bts = bts[1:]
									}
									z.Payload[zgensym_12ee7be02f254da2_6].Key = z.Payload[zgensym_12ee7be02f254da2_6].Key[:0]
								} else {
									z.Payload[zgensym_12ee7be02f254da2_6].Key, bts, err = nbs.ReadBytesBytes(bts, z.Payload[zgensym_12ee7be02f254da2_6].Key)

									if err != nil {
										return
									}
								}
								if err != nil {
									return
								}
							case "Val_zid01_bin":
								found19zgensym_12ee7be02f254da2_20[1] = true
								if nbs.AlwaysNil || msgp.IsNil(bts) {
									if !nbs.AlwaysNil {
										bts = bts[1:]
									}
									z.Payload[zgensym_12ee7be02f254da2_6].Val = z.Payload[zgensym_12ee7be02f254da2_6].Val[:0]
								} else {
									z.Payload[zgensym_12ee7be02f254da2_6].Val, bts, err = nbs.ReadBytesBytes(bts, z.Payload[zgensym_12ee7be02f254da2_6].Val)

									if err != nil {
										return
									}
								}
								if err != nil {
									return
								}
							default:
								bts, err = msgp.Skip(bts)
								if err != nil {
									return
								}
							}
						}
						if nextMiss19zgensym_12ee7be02f254da2_20 != -1 {
							bts = nbs.PopAlwaysNil()
						}

					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss16zgensym_12ee7be02f254da2_17 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of KVFile
var unmarshalMsgFieldOrder16zgensym_12ee7be02f254da2_17 = []string{"Payload_zid00_slc"}

var unmarshalMsgFieldSkip16zgensym_12ee7be02f254da2_17 = []bool{false}

// fields of KV
var unmarshalMsgFieldOrder19zgensym_12ee7be02f254da2_20 = []string{"Key_zid00_bin", "Val_zid01_bin"}

var unmarshalMsgFieldSkip19zgensym_12ee7be02f254da2_20 = []bool{false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *KVFile) Msgsize() (s int) {
	s = 1 + 18 + msgp.ArrayHeaderSize
	for zgensym_12ee7be02f254da2_6 := range z.Payload {
		if z.Payload[zgensym_12ee7be02f254da2_6] == nil {
			s += msgp.NilSize
		} else {
			s += 1 + 14 + msgp.BytesPrefixSize + len(z.Payload[zgensym_12ee7be02f254da2_6].Key) + 14 + msgp.BytesPrefixSize + len(z.Payload[zgensym_12ee7be02f254da2_6].Val)
		}
	}
	return
}
